#!/usr/bin/env bash

# modified shamelessly from https://jade.fyi/blog/pinning-nixos-with-npins/

cd $(dirname $0)

# assume that if there are no args, you want to dry-build the configuration
cmd=${1:-dry-build}
shift

nixpkgs_pin=$(nix-instantiate --eval ./npins -A nixpkgs.outPath |tr -d \")
nix_path="nixpkgs=${nixpkgs_pin}:nixos-config=${PWD}/configuration.nix"

env NIX_PATH="${nix_path}" nixos-rebuild "$cmd" "$@"
